version: "3.4"
services:
  app:
    build:
      context: .
      target: dev
    command: bundle exec rails server -b 0.0.0.0 -p 3003
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - '/app/tmp/pids'
      - './:/app'
    env_file:
      - .env.development
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
